build:
	javac -classpath .:jogl.jar:gluegen-rt.jar cs567/particles/*.java

run:
	java -Xmx1000m -classpath .:jogl.jar:gluegen-rt.jar cs567.particles.ParticleSystemBuilder

doc:
	javadoc -d doc -classpath .:jogl.jar:gluegen-rt.jar cs567.particles